import Head from 'next/head'
import { Heading } from './components/Heading'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading text="Home Page" />
    </div>
  )
}

export default Home